ports:
  - port: 8080
tasks:
- init: python3 -m pip install numpy scipy matplotlib scikit-image scikit-learn opencv-python h5py pandas jupyterlab \
        https://download.pytorch.org/whl/cpu/torch-1.1.0-cp37-cp37m-linux_x86_64.whl &&
        curl https://sdk.cloud.google.com | bash
        #exec -l $SHELL &&
        #echo "Use 'gcloud init' to set up Google Cloud SDK"
